@startuml

actor user
participant GitHub
collections Firebase
box "Google Cloud Platform"
    database bucket as "Cloud Storage"
    participant function as "Cloud Function"
    control job as "Scheduler Job"
end box



user -> GitHub : push content
GitHub -> Firebase : deploy
GitHub -> bucket : update

== Time passes ==

job -> function : publish
function -> bucket : get timestamp
bucket -> function : return timestamp
function -> GitHub : request redeploy
GitHub -> Firebase : deploy
GitHub -> bucket : update
function -> user : email status

@enduml
